"""Tłumaczenia opisów biblioteki; nazwy sygnałów i treść użytkownika zostają bez zmian."""
PL = {
    "Local host-camera preview abstraction, not a physical USB/CSI pinout or camera protocol emulator": "Model lokalnego podglądu kamery urządzenia; nie układ pinów USB/CSI ani emulator protokołu kamery",
    "Grove I2C connector; signal order, not package pin numbering": "Złącze Grove I2C; kolejność sygnałów, nie numeracja obudowy",
    "Two potentiometers and push switch; verify header order": "Dwa potencjometry i przycisk; sprawdź kolejność pinów złącza",
    "Grove connector; 38 kHz demodulated output": "Złącze Grove; zdemodulowane wyjście 38 kHz",
    "Semantic module signals; verify physical order and driver polarity": "Logiczne sygnały modułu; sprawdź kolejność fizyczną i polaryzację sterownika",
    "3-pin carrier, not the bare 4-pin sensor; verify physical order": "Moduł 3-pinowy, nie sam czujnik 4-pinowy; sprawdź kolejność wyprowadzeń",
    "256 LEDs, logical power/data endpoints; verify carrier connectors": "256 diod LED, logiczne zaciski zasilania i danych; sprawdź złącza modułu",
    "4-lead common-anode RGB LED; verify colour pin order": "4-pinowa dioda RGB ze wspólną anodą; sprawdź kolejność pinów kolorów",
    "GL5528 photoresistor; reference resistance is user-configurable": "Fotorezystor GL5528; rezystancja odniesienia jest ustawiana przez użytkownika",
    "Vishay DIP-6, with base connection": "Vishay DIP-6, z wyprowadzeniem bazy",
    "5.1 V DC output abstraction; not a USB-C pinout or USB PD negotiator": "Model wyjścia DC 5,1 V; nie układ pinów USB-C ani negocjator USB PD",
    "40 independent contacts, physical header numbering; no built-in power sources": "40 niezależnych styków, fizyczna numeracja złącza; bez wbudowanych źródeł zasilania",
    "40 independent contacts; verify connector orientation": "40 niezależnych styków; sprawdź orientację złącza",
    "Generic terminal arrangement — verify your device": "Ogólny układ wyprowadzeń — sprawdź swój element",
    "All terminals of the specified variant": "Wszystkie wyprowadzenia podanego wariantu",
    "10-bit, 8-channel SPI ADC; PDIP-16": "10-bitowy, 8-kanałowy przetwornik A/C SPI; PDIP-16",
    "12 terminals; signal/channel identifiers, not physical header numbering. LV/HV grounds are distinct contacts.": "12 wyprowadzeń; oznaczenia sygnałów/kanałów, nie numeracja złącza. Masy LV/HV to osobne styki.",
    "14 main edge contacts; battery pads and camera expansion connector excluded": "14 głównych styków krawędziowych; bez pól akumulatora i złącza kamery",
    "16 main JP1/JP2 contacts; JP3/JP4/JP5 DIAG/INDEX/VREF test pads excluded": "16 głównych styków JP1/JP2; bez pól testowych JP3/JP4/JP5 DIAG/INDEX/VREF",
    "1×2, 2.54 mm; use a custom element for another length": "1×2, 2,54 mm; dla innej długości utwórz własny element",
    "25 front strips including five large rings and 3V/GND guard strips; unconnected rear strips excluded": "25 przednich styków, w tym pięć dużych pól i ochronne styki 3V/GND; bez niepodłączonych tylnych styków",
    "3-pin control + 3 screw terminals, no separate JD-VCC": "3 piny sterowania + 3 zaciski śrubowe, bez osobnego JD-VCC",
    "3-wire hobby servo; verify supply rating for exact model": "Serwomechanizm z 3 przewodami; sprawdź zasilanie konkretnego modelu",
    "4-channel bidirectional BSS138 module, 12 pins": "4-kanałowy dwukierunkowy moduł BSS138, 12 pinów",
    "4-channel optoisolated board; 6-pin input + JD-VCC + 12 relay terminals": "4-kanałowy moduł z optoizolacją; wejście 6-pinowe + JD-VCC + 12 zacisków przekaźników",
    "4-lead common-cathode RGB LED; verify colour pin order": "4-pinowa dioda RGB ze wspólną katodą; sprawdź kolejność pinów kolorów",
    "4-leg normally-open switch; 1=3 and 2=4 internally": "4-pinowy przycisk normalnie otwarty; wewnętrznie połączone 1=3 oraz 2=4",
    "4-pin LM393 flame detector carrier": "4-pinowy moduł czujnika płomienia z LM393",
    "4-pin MQ-2 breakout, not bare six-pin sensor": "4-pinowy moduł MQ-2, nie sam czujnik z 6 pinami",
    "4-wire bipolar motor; NEMA17 specifies mounting size, not wiring colours": "4-przewodowy silnik bipolarny; NEMA17 określa wymiary montażowe, nie kolory przewodów",
    "40-pin GPIO expansion header": "40-pinowe złącze GPIO",
    "40-pin main header": "40-pinowe złącze główne",
    "5-pin auto-gain microphone breakout": "5-pinowy moduł mikrofonu z automatyczną regulacją wzmocnienia",
    "6-pin I2C/SPI breakout; BME280 does not measure gas quality": "6-pinowy moduł I2C/SPI; BME280 nie mierzy jakości gazu",
    "6-pin SPI microSD carrier": "6-pinowy moduł microSD SPI",
    "76 Morpho contacts; Arduino-compatible duplicate headers and ST-LINK connector excluded": "76 styków Morpho; bez powtórzonych złączy Arduino i złącza ST-LINK",
    "8-wire row/column matrix; tail order varies": "8-przewodowa matryca wierszy/kolumn; kolejność przewodów zależy od wariantu",
    "AM2302/DHT22 bare 4-pin sensor": "Sam czujnik AM2302/DHT22, 4 piny",
    "ARK 2-position terminal block": "Listwa zaciskowa ARK, 2 zaciski",
    "ARK 3-position terminal block": "Listwa zaciskowa ARK, 3 zaciski",
    "Adjustable 4-terminal LM2596 breakout": "Regulowany moduł LM2596 z 4 wyprowadzeniami",
    "Adjustable 4-terminal MT3608 breakout": "Regulowany moduł MT3608 z 4 wyprowadzeniami",
    "All 40 main header contacts; SWD test connector excluded": "Wszystkie 40 styków głównego złącza; bez złącza testowego SWD",
    "All 48 main side contacts; Ethernet/USB host/debug/underside memory pads excluded": "Wszystkie 48 głównych styków bocznych; bez Ethernet/USB host/debug i pól pamięci na spodzie",
    "Banana Pi BPI-M5, 40-pin expansion header": "Banana Pi BPI-M5, 40-pinowe złącze rozszerzeń",
    "Bare 4-pin sensor, front view; not 3-pin breakout": "Sam czujnik z 4 pinami, widok od przodu; nie moduł 3-pinowy",
    "Bare incremental encoder with push switch, 5 terminals": "Enkoder inkrementalny z przyciskiem, 5 wyprowadzeń",
    "Blue HD44780-compatible display with LCM1602 I2C backpack": "Niebieski wyświetlacz zgodny z HD44780 z adapterem LCM1602 I2C",
    "Botland MOD-01997; active-low input; optoisolated relay module": "Botland MOD-01997; wejście aktywne stanem niskim; moduł przekaźnika z optoizolacją",
    "Classic Nano, 30 main header contacts": "Klasyczne Nano, 30 styków głównych złączy",
    "DIP-16 (bare IC)": "DIP-16 (sam układ scalony)",
    "ELECFREAKS EF90D / EF09083, continuous rotation with wheel; PWM controls speed and direction, not angle": "ELECFREAKS EF90D / EF09083, ciągły obrót z kołem; PWM steruje prędkością i kierunkiem, nie kątem",
    "ESP-01 2×4 header; logical order, check orientation": "ESP-01, złącze 2×4; kolejność logiczna, sprawdź orientację",
    "ESP32-S3-DevKitC-1 compatible 44-pin variant; NodeMCU clones may differ": "Wariant 44-pinowy zgodny z ESP32-S3-DevKitC-1; klony NodeMCU mogą się różnić",
    "Espressif ESP32-DevKitC V4 / WROOM, 38 contacts": "Espressif ESP32-DevKitC V4 / WROOM, 38 styków",
    "FC-28/YL-69 comparator module, 4-pin host interface": "Moduł komparatora FC-28/YL-69, 4-pinowe złącze sterujące",
    "GY-302 5-pin module": "Moduł GY-302, 5 pinów",
    "GY-521 8-pin breakout": "Moduł GY-521, 8 pinów",
    "GY-GPS6MV2 4-pin UART carrier": "Moduł GY-GPS6MV2 UART, 4 piny",
    "Generic 3-pin demodulating IR receiver module; exact frequency varies": "Ogólny 3-pinowy moduł odbiornika IR z demodulacją; częstotliwość zależy od wariantu",
    "Generic 940 nm IR LED; verify polarity and current": "Ogólna dioda IR 940 nm; sprawdź polaryzację i prąd",
    "Generic G-D-S; choose actual device before wiring": "Ogólny układ G-D-S; wybierz konkretny element przed podłączeniem",
    "Generic SPDT relay, 5 terminals; check package numbering": "Ogólny przekaźnik SPDT, 5 wyprowadzeń; sprawdź numerację obudowy",
    "HC-SR04 4-pin module": "Moduł HC-SR04, 4 piny",
    "HC-SR501 3-pin module": "Moduł HC-SR501, 3 piny",
    "HD44780 with PCF8574 backpack, 4 external pins": "HD44780 z adapterem PCF8574, 4 zewnętrzne piny",
    "Iduino ST1146 microphone module; analog output, exact revision may vary": "Moduł mikrofonu Iduino ST1146; wyjście analogowe, szczegóły zależą od wersji",
    "Iduino ST1167: 2 UART channels; RXI→RXO HV-to-LV; TXI↔TXO bidirectional": "Iduino ST1167: 2 kanały UART; RXI→RXO z HV do LV; TXI↔TXO dwukierunkowo",
    "Leonardo, expansion and ICSP headers": "Leonardo, złącza rozszerzeń i ICSP",
    "MAX7219 matrix module with 5-pin input and output headers": "Moduł matrycy MAX7219 z 5-pinowymi złączami wejścia i wyjścia",
    "MB102-style, breadboard outputs plus 2×2 power header; variant-dependent": "Typ MB102, wyjścia płytki stykowej i złącze zasilania 2×2; zależne od wariantu",
    "MFRC522 8-pin SPI carrier": "Moduł MFRC522 SPI, 8 pinów",
    "Main user expansion headers; USB/HDMI/camera sockets are not individual schematic pins": "Główne złącza rozszerzeń; gniazda USB/HDMI/kamery nie są osobnymi pinami schematu",
    "Mega 2560 Rev3, expansion and main ICSP headers": "Mega 2560 Rev3, złącza rozszerzeń i główne ICSP",
    "Multiwatt15 (bare IC, not red driver module)": "Multiwatt15 (sam układ scalony, nie czerwony moduł sterownika)",
    "NUCLEO-F401RE MB1136, CN7/CN10 Morpho headers": "NUCLEO-F401RE MB1136, złącza Morpho CN7/CN10",
    "Orange Pi 3 LTS, 26-pin header, user manual v2.1 section 3.17": "Orange Pi 3 LTS, złącze 26-pinowe, instrukcja v2.1 rozdział 3.17",
    "Pololu-compatible A4988 carrier, 2×8 header": "Moduł A4988 zgodny z Pololu, złącza 2×8",
    "Protected TP4056 module with DW01A, 6 solder terminals": "Moduł TP4056 z zabezpieczeniem DW01A, 6 pól lutowniczych",
    "Raspberry Pi 40-pin HAT, SPI control header": "40-pinowa nakładka HAT Raspberry Pi, złącze sterujące SPI",
    "SOT-223, tab = OUT": "SOT-223, płytka chłodząca = OUT",
    "SPDT, 3 terminals": "SPDT, 3 wyprowadzenia",
    "SSD1306 4-pin I2C module; VCC/GND order varies on clones": "4-pinowy moduł SSD1306 I2C; kolejność VCC/GND może się różnić w klonach",
    "ST7735 8-pin display header; SD connector not included": "8-pinowe złącze wyświetlacza ST7735; bez złącza SD",
    "Six named external terminals; identifiers follow board labels, not physical numbering": "Sześć nazwanych wyprowadzeń; identyfikatory według napisów na płytce, nie numeracji fizycznej",
    "TO-220 G-D-S; tab connected to D": "TO-220 G-D-S; płytka chłodząca połączona z D",
    "TO-220, pins 1..3": "TO-220, piny 1..3",
    "TO-92, flat front view; cable colours are not pin numbers": "TO-92, widok od płaskiego przodu; kolory przewodów nie oznaczają numerów pinów",
    "Teensy 4.1, 48 main side contacts, L/R counted from USB end": "Teensy 4.1, 48 głównych styków bocznych; L/R liczone od strony USB",
    "Three servo leads identified by signal; verify connector orientation": "Trzy przewody serwa oznaczone sygnałami; sprawdź orientację złącza",
    "UNO Rev3, expansion and ATmega328P ICSP headers": "UNO Rev3, złącza rozszerzeń i ICSP ATmega328P",
    "Unidentified part; legacy pin layout is unverified. Supply the exact datasheet before use.": "Niezidentyfikowany element; dawny układ pinów niezweryfikowany. Przed użyciem dostarcz właściwą dokumentację.",
    "VSSOP-10 (not a breakout module)": "VSSOP-10 (nie moduł na płytce)",
    "Watterott SilentStepStick TMC2208 v1.2; UART/CLK contacts depend on solder bridges": "Watterott SilentStepStick TMC2208 v1.2; styki UART/CLK zależą od mostków lutowniczych",
    "XIAO ESP32-S3 Sense, 14 castellated main edge contacts": "XIAO ESP32-S3 Sense, 14 głównych styków krawędziowych z półotworami",
    "ZS-040 6-pin carrier, not bare 34-pad HC-05 radio": "6-pinowy moduł ZS-040, nie sam układ radiowy HC-05 z 34 polami",
    "ZS-042 6-pin main header; duplicate 4-pin header not modelled": "ZS-042, główne złącze 6-pinowe; bez powtórzonego złącza 4-pinowego",
    "micro:bit V2, 25 edge-connector strips from left to right (front view)": "micro:bit V2, 25 styków krawędziowych od lewej do prawej (widok z przodu)",
    "onsemi PN2222 TO-92, pins 1 E / 2 B / 3 C": "onsemi PN2222 TO-92, piny 1 E / 2 B / 3 C",
    "onsemi TO-92, C-B-E pin order": "onsemi TO-92, kolejność pinów C-B-E",
}


def catalog_text(text, language):
    if language != "pl":
        return text
    if text.startswith("Standard ") and text.endswith(" Gate schematic symbol"):
        return "Standardowy symbol bramki " + text[9:-22]
    if " logic, " in text:
        gate, package = text.split(" logic, ", 1)
        return "Bramka " + gate + ", " + package
    return PL.get(text, text)
